<?php

namespace AppBundle\Repository;

/**
 * View1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use Doctrine\ORM\EntityRepository;


class View1Repository extends \Doctrine\ORM\EntityRepository
{



public function findall()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:View1 p'
            )
            ->getResult();
    }


}
